version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stack
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysqlbd1
volumes:
  mysql-data:
