version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: stack
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: db
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "$PWD/datalake:/data"
    command: server /data --console-address ":9001"
  airflow:
    image: apache/airflow:2.1.1-python3.8
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/airflow/dags:/opt/airflow/dags/"
    entrypoint: /bin/bash
    command: -c '(airflow db init && airflow users create --username admin --password stack --firstname Renan --lastname Silva --role Admin --email admin@example.org); airflow webserver & airflow scheduler'
volumes:
  postgres-data:
